#!/bin/bash

a_flag='false'
b_flag='false'
y_flag='false'
filesites=''
verbose='false'

print_usage() {
  printf "Usage:\n"
  printf "xcsites [options] [arguments]\n\n"
  printf "options:\n"
  printf "-h|?            Affiche cette aide | show brief help\n"
  printf "-a              A utiliser avec l'option 'f' pour entrer un chemin absolu\n"
  printf "-[a]f FICHIER   Nom/Chemin du FICHIER des sites à gérer\n"
  printf "-y              Confirmation automatique\n"
  printf "-b              (inactif actuellement)\n"
  printf "-v              Verbeux (inactif actuellement)\n"
}

while getopts 'abyf:vh?' flag; do
  case "${flag}" in
    a) a_flag='true' ;;
    b) b_flag='true' ;;
    y) y_flag='true' ;;
    f) filesites="${OPTARG}" ;;
    v) verbose='true' ;;
    h|?) print_usage
       exit 1 ;;
  esac
done

shift $(($OPTIND - 1))
#printf "Remaining arguments are: %s\n" "$*"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
#printf "DIR: $DIR \n"
# Absolute path to this script. /home/user/bin/foo.sh
SCRIPT=$(readlink -f $0)
# Absolute path this script is in. /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`
#printf "SCRIPT: $SCRIPT / SCRIPTPATH: $SCRIPTPATH \n"

if [ ! -z "$filesites" ]; then
    #printf 'Option -f "%s" specified\n' "$filesites"
    if [ $a_flag = 'false' ]; then
        filename=$SCRIPTPATH/$filesites
    else 
        filename=$filesites
    fi
else
    filename=$SCRIPTPATH/sites.txt
fi

DORIGINE=`pwd`
IDSITE=1
printf "\e[94m\n"
printf "  #####################################################\n"
printf "  #  Script de gestion de plusieurs instances drupal  #\n"
printf "  #                 [ version 0.5 ]                   #\n"
printf "  #####################################################\n\n"

printf "\e[39mListe les instances à traiter (voir : $filename) : \n"

while IFS= read -r dpath; 
do
        #Si la ligne est commentée on passe a la suivante
        if [[ ${dpath:0:1} == '#' ]]; then
                continue
        fi
        printf "  => \e[94m(\e[1m $IDSITE \e[21m)\e[39m $dpath \n";
        ((IDSITE=IDSITE+1))
done < $filename
((IDSITE=IDSITE-1))


# 2ème parametre
if [ $# -ne 2 ]
then
        SITETOUSE="ALL"
else
        SITETOUSE=$2
fi

# Infos & Confirmation:
if test "$1" == "" 
   then 
     printf "\nIl manque la commande à exécuter ;-)\n" 
     printf "Exemples : xcsites \"drush status\"\n"
     printf "           xcsites \"composer require drupal/coffee:1.x-dev@dev\"\n"
     printf "           xcsites \"composer update\" 2  <-- (pour exécuter seulement sur le site n°2)\n"
     exit 1 
   else
     printf "\nExécuter la commande :\e[94m\e[1m $1 \e[21m\e[39m\n"
     if [ $SITETOUSE = "ALL" ]
     then
             printf "                       sur tous les sites listés [$IDSITE site(s)]\n"
     else
             printf "                       sur le site numéro\e[94m\e[1m $SITETOUSE \e[21m\e[39m\n"
     fi
fi

getConfirmContinue() {
    local REPONSE=""

    echo -e "                       \e[47m\e[31m\e[1m Confirmez ? [oui|yes|o|y] \e[21m\e[39m\e[49m : \c"
    read REPONSE
    if test "$REPONSE" != "o" -a "$REPONSE" != "y" -a "$REPONSE" != "yes" -a "$REPONSE" != "oui"
#    if [[ $REPONSE != "o" || $REPONSE != "y" ]]
    then
        printf "\e[90m                       --> Commande annulé, car non confirmée.\e[39m\n"
        exit 1
    else
        return 0
    fi
}
if [[ $y_flag != 'true' ]]; then
        getConfirmContinue
fi

IDSITE=1

printf "\e[90m\e[4mDébut:\e[24m\e[39m\n"

while IFS= read -r dpath; 
do
        #Si la ligne est commentée on passe a la suivante
        if [[ ${dpath:0:1} == '#' ]]; then
                continue
        fi

        #ALL sites ou un seul.
        if [[ $SITETOUSE = "ALL" || $IDSITE = $SITETOUSE ]]; then
                printf "\n\e[90msite \e[94m(\e[1m $IDSITE \e[21m)\e[90m >> $dpath <<\e[39m\n\n";
                if  cd $dpath 
                then
                        $1
                else
                        printf "Rien à faire ici ...\n"
                fi
        fi
        ((IDSITE=IDSITE+1))

done < $filename

cd $DORIGINE
printf "\n\e[90m\e[4mFin..\e[24m\e[39m\n"
